server:
    port: 8092
    contextPath: /
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: YUVBfTCei28UciXaWWNbRGSSfH9hBv
      clientSecret: 69M9twm51UrpRObklmdGIV1np1WIbI
      accessTokenUri: http://localhost:8091/oauth/token
      userAuthorizationUri: http://localhost:8091/oauth/authorize
    resource:
      userInfoUri: http://localhost:8091/wp-json/wp/v2/users/me
spring:
  thymeleaf:
    cache: false